### PR TITLE
Update flybase json examples

### PR DESCRIPTION
**Pull request by sjm41**
Revised FLYBASE:FBtr0346876 entry with current FlyBase data (FB2017_06).
Added 'locusTag' and gene 'url' fields to all examples.
Added additional gene synonyms where necessary.
Few other tweaks to mirror data in FB2017_06 (e.g. the SO term in FB for CR46004-RA is currently just for "ncRNA" and not (unfortunately) "lncRNA".)

### CODE REVIEW

**Comment by blakesweeney** [comment]
Thanks for fixing the examples! There were some minor syntax issues so I fixed those and merged the changes. I think this covers all the basic information we need from FlyBase.

**Comment by sjm41** [comment]
Ah, I meant to say that I probably had made some errors with the syntax….

Also, I decided not to try to add publications (to the ncrna section) at this time - there are a couple of issues we’d have to think about & resolve before FB could do that:
i) publication links are almost always made to genes rather than individual transcripts
ii) gene-publication associations can mean anything from ‘the gene is mentioned once in a table in the paper” to “the paper is solely focussed on this gene”.  We have recently introduced some algorithms in FlyBase to highlight those papers that really focus on the gene (done by assessing the amount of data associations to that gene from that paper), but most ncRNA genes don’t have sufficient literature for this algorithm to work on…

Finally, I think there should be a place in the json file to state the FlyBase release (e.g. the current public release that the examples are based on is “FB2017_06”).
In the flybase json example, there is a field called “release” in the metaData section - is that the appropriate place for this information?  If so, can we change the current entry of “2.0” to “FB2017_06”?


steven.

**Comment by blakesweeney** [comment]
We will be happy to take publications when you think you have a good method for finding them. RNAcentral will be working on detecting and assigning publications to sequences eventually as well. 

The version field in metaData is where the version of the database used would go. I have updated the example to reflect the correct version. Thanks for the feedback!

**Comment by sjm41** [comment]
OK, thanks!

**Pull request merged**
